include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/_deployment.yml'

stages:
  - deploy

.deploy-caddy:
  extends: .deploy
  variables:
    COMPOSE_FILE: docker-compose.caddy.yml
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_caddy
  environment:
    url: https://motion.${DD_TRAEFIK_DOMAIN}

.deploy-motion:
  extends: .deploy
  variables:
    FORCE_DOCKER_COMPOSE: 1
    OMIT_CLEAN_DEPLOY: 1
    COMPOSE_FILE: docker-compose.motion.yml
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}

.deploy-branch: &deploy-branch
  only:
    - branches
  except:
    - schedules

.deploy-tag: &deploy-tag
  only:
    - tags

deploy-caddy-branch:
  extends: .deploy-caddy
  <<: *deploy-branch

deploy-motion-branch:
  extends: .deploy-motion
  <<: *deploy-branch

deploy-caddy-tag:
  extends: .deploy-caddy
  <<: *deploy-tag

deploy-motion-tag:
  extends: .deploy-motion
  <<: *deploy-tag
