version: '2.4'

services:
  motion:
    image: ${MOTION_IMAGE_NAME:-pedroetb/motion}:${MOTION_IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME}
    environment:
      TZ:
    networks:
      motion-net:
    volumes:
      - ./config-motion:/usr/local/etc/motion
      - motion-vol:/var/lib/motion
    devices:
      - ${VIDEO_DEVICE:-/dev/video0}
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:${UI_PORT}
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    restart: always
    cpus: '${CPUS:-1}'
    mem_limit: ${MEM_LIMIT:-64M}
    mem_reservation: ${MEM_RESERVATION:-32M}

networks:
  motion-net:
    name: ${MOTION_NET_NAME}
    driver: ${MOTION_NET_DRIVER}
    external: true

volumes:
  motion-vol:
    name: ${MOTION_VOL_NAME:-motion-vol}
    driver: local
    driver_opts:
      type: ${MOTION_VOL_TYPE}
      o: ${MOTION_VOL_OPTIONS}
      device: ${MOTION_VOL_DEVICE}
