version: '3.7'

services:
  caddy:
    image: ${CADDY_IMAGE_NAME:-productionwentdown/caddy}:${CADDY_IMAGE_TAG:-1.0.3}
    environment:
      UI_PORT:
      STREAM_PORT:
      CONTAINER_NAME:
      CADDY_UI_PORT:
      CADDY_STREAM_PORT:
    networks:
      motion-net:
      traefik-net:
    configs:
      - source: caddyfile-config
        target: /etc/Caddyfile
    volumes:
      - work-vol:/etc/.caddy
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-3s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.http.routers.motion-ui.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.motion-ui.tls.certresolver: ${TRAEFIK_CERTRESOLVER}
        traefik.http.routers.motion-ui.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.middlewares.motion-ui-auth.basicauth.users: ${TRAEFIK_UI_AUTH}
        traefik.http.routers.motion-ui.middlewares: motion-ui-auth
        traefik.http.services.motion-ui.loadbalancer.server.port: ${CADDY_UI_PORT}

        traefik.http.routers.motion-stream.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.motion-stream.tls.certresolver: ${TRAEFIK_CERTRESOLVER}
        traefik.http.routers.motion-stream.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) && PathPrefix(`/{id:[0-9]+}`)
        traefik.http.middlewares.motion-stream-auth.basicauth.users: ${TRAEFIK_STREAM_AUTH}
        traefik.http.routers.motion-stream.middlewares: motion-stream-auth
        traefik.http.services.motion-stream.loadbalancer.server.port: ${CADDY_STREAM_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  motion-net:
    name: ${MOTION_NET_NAME}
    driver: ${MOTION_NET_DRIVER}
    attachable: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-motion-caddyfile}
    file: ./config-caddy/Caddyfile

volumes:
  work-vol:
    name: ${WORK_VOL_NAME:-motion-work-vol}
